[package]
name = "crystalrake"
version = "0.1.0"
edition = "2021"
readme = "README.md"
authors = ["minor <minoru113@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
